help_template = ('<div style="border: 1px solid pink">'
'<h1 data-md="#">!wordle help</h1>'
    '<table>'
        '<thead></thead>'
        '<tbody>'
            '<tr>'
                '<td>Help</td>'
                '<td></td>'
                '<td>What you are seeing right now</td>'
            '</tr>'
            '<tr>'
                '<td>Start</td>'
                '<td></td>'
                '<td>Register for the game</td>'
            '</tr>'
            '<tr>'
                '<td>Guess</td>'
                '<td>{word} <i data-md="*">optional</i></td>'
                '<td>Get an overview of your guesses of today or take a guess at what todays wordle might be</td>'
            '</tr>'
            '<tr>'
                '<td>Score</td>'
                '<td></td>'
                '<td>Get an overview of the players scores</td>'
            '</tr>'
            '<tr>'
                '<td>Date</td>'
                '<td>{yyyy-mm-dd}</td>'
                '<td>Get the Wordle for a specific date</td>'
            '</tr>'
        '</tbody>'
    '</table>'
                 '<p>Example: !wordle start</p>'
'</div>')